-- Generated by tools/upload_art.py: uploaded UI icon images
return {
	bag = "rbxassetid://80636888954209",
	cash = "rbxassetid://124671912007769",
	daily = "rbxassetid://80149749716210",
	egg = "rbxassetid://95294248934489",
	gift = "rbxassetid://121768957025862",
	index = "rbxassetid://124129669831353",
	lock = "rbxassetid://140061031556644",
	luck = "rbxassetid://112385313162730",
	plus = "rbxassetid://134634388892822",
	rebirth = "rbxassetid://124807624516968",
	shop = "rbxassetid://83584132075422",
	slots = "rbxassetid://127503805222830",
	speed = "rbxassetid://109670955913717",
	starter = "rbxassetid://81594738780820",
	vault = "rbxassetid://73878953271634",
	vip = "rbxassetid://95654112587514",
}
