"""Upload Crystal Garden art + sounds via the Open Cloud Assets API and write the Lua modules the game reads.

Usage: ROBLOX_API_KEY_FILE=path python3 games/crystal/tools/upload.py <creatorUserId> icons|sfx
  icons: games/crystal/art/icons/*.png -> games/crystal/src/Assets.lua (cache: art/icons/uploaded.json, by content hash)
  sfx:   games/crystal/art/sfx/sprite.ogg -> games/crystal/src/Sounds.lua (cache: art/sfx/uploaded.json)
"""
import hashlib
import json
import os
import pathlib
import sys
import time
import urllib.request
import uuid

GAME = pathlib.Path(__file__).resolve().parents[1]
KEY = pathlib.Path(os.environ["ROBLOX_API_KEY_FILE"]).read_text().strip()
CREATOR = sys.argv[1]
MODE = sys.argv[2]


def request(method, url, body=None, headers=None):
    req = urllib.request.Request(url, data=body, method=method, headers={"x-api-key": KEY, **(headers or {})})
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())


def upload(path, asset_type, mime, name, desc):
    boundary = uuid.uuid4().hex
    meta = {"assetType": asset_type, "displayName": name, "description": desc,
            "creationContext": {"creator": {"userId": CREATOR}}}
    parts = [
        f"--{boundary}\r\nContent-Disposition: form-data; name=\"request\"\r\nContent-Type: application/json\r\n\r\n".encode()
        + json.dumps(meta).encode() + b"\r\n",
        f"--{boundary}\r\nContent-Disposition: form-data; name=\"fileContent\"; filename=\"{path.name}\"\r\n"
        f"Content-Type: {mime}\r\n\r\n".encode() + path.read_bytes() + b"\r\n",
        f"--{boundary}--\r\n".encode(),
    ]
    op = request("POST", "https://apis.roblox.com/assets/v1/assets", b"".join(parts),
                 {"Content-Type": f"multipart/form-data; boundary={boundary}"})
    for _ in range(60):
        if op.get("done"):
            return op["response"]["assetId"]
        time.sleep(2)
        op = request("GET", f"https://apis.roblox.com/assets/v1/{op['path']}")
    raise RuntimeError(f"upload of {path.name} did not finish")


def icons():
    folder = GAME / "art" / "icons"
    cache_file = folder / "uploaded.json"
    cache = json.loads(cache_file.read_text()) if cache_file.exists() else {}
    for png in sorted(folder.glob("*.png")):
        digest = hashlib.sha1(png.read_bytes()).hexdigest()
        if cache.get(png.stem, [None])[0] == digest:
            continue
        cache[png.stem] = [digest, upload(png, "Image", "image/png", f"cg-{png.stem}", "Crystal Garden UI icon")]
        print("uploaded", png.stem, cache[png.stem][1])
        cache_file.write_text(json.dumps(cache, indent=1, sort_keys=True))
    lua = ["-- Generated by games/crystal/tools/upload.py: uploaded UI icon images", "return {"]
    for name, (_, asset_id) in sorted(cache.items()):
        lua.append(f'\t{name} = "rbxassetid://{asset_id}",')
    lua.append("}")
    (GAME / "src" / "Assets.lua").write_text("\n".join(lua) + "\n")


def sfx():
    folder = GAME / "art" / "sfx"
    sprite = folder / "sprite.ogg"
    cache_file = folder / "uploaded.json"
    digest = hashlib.sha1(sprite.read_bytes()).hexdigest()
    cache = json.loads(cache_file.read_text()) if cache_file.exists() else {}
    if digest not in cache:
        cache[digest] = upload(sprite, "Audio", "audio/ogg", "crystal-sfx", "Crystal Garden sound effects (Kenney CC0)")
        cache_file.write_text(json.dumps(cache, indent=1))
        print("uploaded sprite", cache[digest])
    regions = json.loads((folder / "sprite.json").read_text())
    lua = ["-- Generated by games/crystal/tools/upload.py: one audio sprite, played by region (start, length in seconds)",
           "return {", f'\tId = "rbxassetid://{cache[digest]}",', "\tClips = {"]
    for name, (start, length) in regions.items():
        lua.append(f"\t\t{name} = {{ {start}, {length} }},")
    lua += ["\t},", "}"]
    (GAME / "src" / "Sounds.lua").write_text("\n".join(lua) + "\n")


{"icons": icons, "sfx": sfx}[MODE]()
print("done", MODE)
