"""Upload art/icons/*.png to Roblox (Open Cloud Assets API) and write games/<game>/src/Assets.lua.

Usage: ROBLOX_API_KEY_FILE=path python3 tools/upload_art.py <creatorUserId> [game]
Already-uploaded icons are cached in art/uploaded.json and skipped.
"""
import json
import os
import pathlib
import sys
import time
import urllib.request
import uuid

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICONS = ROOT / "art" / "icons"
CACHE = ROOT / "art" / "uploaded.json"
KEY = pathlib.Path(os.environ["ROBLOX_API_KEY_FILE"]).read_text().strip()
CREATOR = sys.argv[1]
GAME = sys.argv[2] if len(sys.argv) > 2 else "eggs"


def request(method, url, body=None, headers=None):
    req = urllib.request.Request(url, data=body, method=method, headers={"x-api-key": KEY, **(headers or {})})
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())


def upload(path):
    boundary = uuid.uuid4().hex
    meta = {"assetType": "Image", "displayName": f"ui-{path.stem}", "description": "UI icon",
            "creationContext": {"creator": {"userId": CREATOR}}}
    parts = [
        f"--{boundary}\r\nContent-Disposition: form-data; name=\"request\"\r\nContent-Type: application/json\r\n\r\n".encode()
        + json.dumps(meta).encode() + b"\r\n",
        f"--{boundary}\r\nContent-Disposition: form-data; name=\"fileContent\"; filename=\"{path.name}\"\r\n"
        f"Content-Type: image/png\r\n\r\n".encode() + path.read_bytes() + b"\r\n",
        f"--{boundary}--\r\n".encode(),
    ]
    op = request("POST", "https://apis.roblox.com/assets/v1/assets", b"".join(parts),
                 {"Content-Type": f"multipart/form-data; boundary={boundary}"})
    for _ in range(30):
        if op.get("done"):
            return op["response"]["assetId"]
        time.sleep(1)
        op = request("GET", f"https://apis.roblox.com/assets/v1/{op['path']}")
    raise RuntimeError(f"upload of {path.name} did not finish")


cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
for png in sorted(ICONS.glob("*.png")):
    if png.stem in cache:
        continue
    cache[png.stem] = upload(png)
    print("uploaded", png.stem, cache[png.stem])
    CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True))

lua = ["-- Generated by tools/upload_art.py: uploaded UI icon images", "return {"]
for name, asset_id in sorted(cache.items()):
    lua.append(f'\t{name} = "rbxassetid://{asset_id}",')
lua.append("}")
out = ROOT / "games" / GAME / "src" / "Assets.lua"
out.write_text("\n".join(lua) + "\n")
print("wrote", out)
