"""Upload art/sfx/sprite.ogg as a Roblox Audio asset and write games/<game>/src/Sounds.lua.

Usage: ROBLOX_API_KEY_FILE=path python3 tools/upload_sfx.py <creatorUserId> [game]
The asset id is cached in art/sfx/uploaded.json, keyed by the sprite's sha1, so an unchanged sprite isn't re-uploaded.
"""
import hashlib
import json
import os
import pathlib
import sys
import time
import urllib.request
import uuid

ROOT = pathlib.Path(__file__).resolve().parent.parent
SFX = ROOT / "art" / "sfx"
CACHE = SFX / "uploaded.json"
KEY = pathlib.Path(os.environ["ROBLOX_API_KEY_FILE"]).read_text().strip()
CREATOR = sys.argv[1]
GAME = sys.argv[2] if len(sys.argv) > 2 else "eggs"


def request(method, url, body=None, headers=None):
    req = urllib.request.Request(url, data=body, method=method, headers={"x-api-key": KEY, **(headers or {})})
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())


def upload(path):
    boundary = uuid.uuid4().hex
    meta = {"assetType": "Audio", "displayName": "sfx-sprite", "description": "Game sound effects (Kenney CC0)",
            "creationContext": {"creator": {"userId": CREATOR}}}
    parts = [
        f"--{boundary}\r\nContent-Disposition: form-data; name=\"request\"\r\nContent-Type: application/json\r\n\r\n".encode()
        + json.dumps(meta).encode() + b"\r\n",
        f"--{boundary}\r\nContent-Disposition: form-data; name=\"fileContent\"; filename=\"{path.name}\"\r\n"
        f"Content-Type: audio/ogg\r\n\r\n".encode() + path.read_bytes() + b"\r\n",
        f"--{boundary}--\r\n".encode(),
    ]
    op = request("POST", "https://apis.roblox.com/assets/v1/assets", b"".join(parts),
                 {"Content-Type": f"multipart/form-data; boundary={boundary}"})
    for _ in range(60):
        if op.get("done"):
            return op["response"]["assetId"]
        time.sleep(2)
        op = request("GET", f"https://apis.roblox.com/assets/v1/{op['path']}")
    raise RuntimeError("audio upload did not finish")


sprite = SFX / "sprite.ogg"
digest = hashlib.sha1(sprite.read_bytes()).hexdigest()
cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
if digest not in cache:
    cache[digest] = upload(sprite)
    CACHE.write_text(json.dumps(cache, indent=1))
    print("uploaded sprite", cache[digest])
regions = json.loads((SFX / "sprite.json").read_text())

lua = ["-- Generated by tools/upload_sfx.py: one audio sprite, played by region (start, length in seconds)",
       "return {", f'\tId = "rbxassetid://{cache[digest]}",', "\tClips = {"]
for name, (start, length) in regions.items():
    lua.append(f"\t\t{name} = {{ {start}, {length} }},")
lua += ["\t},", "}"]
out = ROOT / "games" / GAME / "src" / "Sounds.lua"
out.write_text("\n".join(lua) + "\n")
print("wrote", out)
